name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: echo $HEROKU_API_KEY | heroku auth:token

    - name: Build and Test Spring Boot App
      run: |
        cd maturemissions
        ./gradlew clean build -Dspring.profiles.active=test

    - name: Deploy Spring Boot App
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cd maturemissions
        heroku plugins:install heroku-cli-deploy
        heroku deploy:jar build/libs/maturemissions-0.0.1-SNAPSHOT.jar --app maturemissions

    - name: Build and Deploy React App
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cd mature-missions
        git init
        git remote add heroku https://git.heroku.com/maturemissions-frontend.git
        git add .
        git commit -m "Deploy React app"
        git push -f heroku master
